spring:
   datasource:
      driverUrl: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      driver: oracle.jdbc.driver.OracleDriver
      dialect: org.hibernate.dialect.Oracle10gDialect
      user: agile
      password: agile